### ISSUE TITLE
Doesn't work with OOT

### ISSUE THREAD

**Issue by Starkium** [JamesO2x/Py-MM3D-LZSS-decompressor-to-CMB#1]
Figured this script would have worked with oot files, but it doesn't appear to. I do see the name is MM3D 😅

**Comment by JamesO2x** [comment]
The script should output a file called "check_head_log.txt" as a log file. Could you paste its content here? Or at least a few lines of the log as a sample?

**Comment by tonymckendry** [comment]
I know it's been awhile, but I thought I'd try out your tool for OOT3D and couldn't get it to work. 
here's the check_head_log output: 
```
b'ZSI\x01', .\zsi\spot10_1_info.zsi
---, .\check_head_log.txt
---, .\cmb_cleanup.exe
---, .\zsi_cleanup.exe
---, .\zsi_conversion.exe
```

**Comment by JamesO2x** [comment]
Ah, ok thanks. The part of the log that says `b'ZSI\x01'` tells me that this OoT file is using a header format that is slightly different from MM. I didn't test the script for OoT files, but it should be an easy fix, assuming that the overall format of OoT's ZSI files are the same.

UPDATE: Done. The new script should work with OoT3D files. it was an easy fix. I tested a few OoT3D files, but let me know if you have any issues.

I also significantly improved the options in the script, the log files, the clean up script, and recompiled the EXEs. Overall it should be a lot easier to use now, and less prone to errors. I recommend completely deleting the old version you have and using this new one.

**Comment by JamesO2x** [comment]
I'm gonna close this issue because OoT conversion should work now.
